### ISSUE TITLE
Bootstrapper package installation should use pinned versions

### ISSUE THREAD

**Issue by kevin-bates** [elyra-ai/kfp-notebook#17]
When an image associated with a pipeline node runs, the bootstrapper script ensures that the set of python packages it needs are their latest versions.  It does this by running the equivalent of `pip install --upgrade <package>` for each of the top-level packages it requires.  This has the following issues:

1. The `--upgrade` flag, by default, updates the top level packages to their latest versions, but does not ensure that dependent packages are also updated to their latest versions.  This can lead to the behavior found in https://github.com/elyra-ai/elyra/issues/437 where the image container still referenced an older submodule.  Using `--upgrade-strategy=eager` would trigger the updates of all packages to their latest versions - which could also break upstream dependencies.
2. The fact that the bootstrapper runs on every container invocation implies that, should one of these updated versions introduce a fatal issue, exactly **zero** notebook nodes will succeed at the point in which the flawed package has been released and until the flaw has been addressed.  These failures will be global.
3. The primary tenant of containers is that they introduce reproducibility.  However, by updating even the top level dependencies to their latest version on each invocation implies that two otherwise identical runs could produce different results.

I believe we should build a manifest of explicit versions for each of the top-level dependencies we need and perform the `pip install --upgrade <package>==<version>`.  In addition, this manifest should reside within the repository and be referenced by documentation so that users have a means of preparing their own images for use by kfp-notebook.

Here are the top-level packages that the bootstrapper deploys: `minio`, `argparse`, `papermill`, `nbconvert`, `nbformat`, `ipykernel`.   Since important packages like `jupyter_client` and `ipython` are not represented, it would be a good idea to include them as well.

Here are their versions as of right now...
```
minio==5.0.10
argparse==1.4.0
papermill==2.1.1
nbconvert==5.6.1
nbformat==5.0.6
ipykernel==5.2.1

jupyter_client==6.1.3
ipython==7.13.0
```
We should use these versions - or whatever we qualify with - to produce _somewhat_[*] consistent, reproducible results.

[*] Note: we should ideally have a complete manifest of sub-packages to totally eliminate the possibility of failure on each run.  Another option would be to use an [init container](#16) which houses _previously installed_ versions and prepend those packages to the packages of the target container.

**Comment by lresende** [comment]
Also, if a given image already has an old version of a given dependency (e.g. jupyter_client) then it does not get updated which I think we should always update particularly if we want to get to a set version.
