### ISSUE TITLE
Add support for git-based package sources to requirements file

### ISSUE THREAD

**Issue by kevin-bates** [elyra-ai/kfp-notebook#73]
The current format for specifying packages in [`requirements-elyra.txt`](https://github.com/elyra-ai/kfp-notebook/blob/master/etc/requirements-elyra.txt) is fixed on a `package==version` format.  It would be helpful to be able to support `git` formatting such that if specified the `==version` portion does not come into play.  This would ease the pain when specifying packages whose changes may still be under development, etc.

Some examples that appear to work:

org/repo@branch...
`pip install git+https://github.com/kevin-bates/elyra@support-eg-in-runtimes`

org/repo@commit_sha
`pip install git+https://github.com/kevin-bates/elyra@07a768514e5353f58878794b26e19b438a62e1de`

**Comment by kevin-bates** [comment]
Hmm.  I'm not so sure we want to do this.  After making the changes I went to test and ran into the following:
```
Collecting git+https://github.com/kevin-bates/elyra@support-eg-in-runtimes
  Cloning https://github.com/kevin-bates/elyra (to revision support-eg-in-runtimes) to /tmp/pip-req-build-pq8uagah
  Running command git clone -q https://github.com/kevin-bates/elyra /tmp/pip-req-build-pq8uagah
  ERROR: Error [Errno 2] No such file or directory: 'git': 'git' while executing command git clone -q https://github.com/kevin-bates/elyra /tmp/pip-req-build-pq8uagah
ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?
```
Since `git` is a command, we would need to "require" the runtime image to also support `git` (along with `curl` and `python`).   Should we even go down this road?  Since this is primarily for elyra development purposes and we can add a dev-version of a wheel file into the image when needed, I think it might be best to not push the burden to the user/image.

@lresende, @akchinSTC - do you agree?

**Comment by akchinSTC** [comment]
adding another required package to our requirements is iffy but simple enough to as part of our bootstrapping routine, with that said, the whole idea was to use community provided images so that we wouldnt have to maintain them and users could bring in whatever they wanted, and yet here we are maintaining a copy of the images in quay.io due to the dockerhub rate issue right now.  I dont have strong feelings either way

**Comment by kevin-bates** [comment]
Ok - thanks.  Yeah, since we're trying to be flexible on the community images front and since this will likely only happen during development - where _we_ can workaround things - I'm going to close this issue.
